version: "3.9"

services:
  db:
    image: postgres:16
    container_name: maville_db
    environment:
      POSTGRES_USER: maville
      POSTGRES_PASSWORD: maville
      POSTGRES_DB: maville
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
